apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
